GET http://localhost:3000/livros/

###

GET http://localhost:3000/livros/2

###

POST http://localhost:3000/livros/
Content-Type: application/json

{ 
  "titulo": "Portugol para Iniciantes", 
  "autor": "Jade Smith" 
}

###

PUT http://localhost:3000/livros/4
Content-Type: application/json

{ 
  "titulo": "Pagode da Amarelinha", 
  "autor": "Grupo Molejo" 
}

###

DELETE http://localhost:3000/livros/1
